import richBlockType from '../../customFields/richBlockType'

export default {
  name: 'cartPageConfig',
  description: '',
  type: 'document',
  title: 'CartPageConfig',
  fields: [
    {
      title: 'Name',
      name: 'name',
      description: '',
      type: 'string',
    },
    {
      title: 'EmptyCartMessage',
      name: 'emptyCartMessage',
      ...richBlockType,
    },
    {
      title: 'EmptyCartLeftCTA',
      name: 'emptyCartLeftCTA',
      ...richBlockType,
    },
    {
      title: 'EmptyCartRightCTA',
      name: 'emptyCartRightCTA',
      ...richBlockType,
    },
    {
      title: 'PromoTextMobile',
      name: 'promoTextMobile',
      ...richBlockType,
    },
    {
      title: 'PromoTextDesktop',
      name: 'promoTextDesktop',
      ...richBlockType,
    },
    {
      title: 'FooterLeftCTA',
      name: 'footerLeftCTA',
      ...richBlockType,
    },
    {
      title: 'FooterRightCTA',
      name: 'footerRightCTA',
      ...richBlockType,
    },
    {
      title: 'ProductLimit',
      name: 'productLimit',
      description: '',
      type: 'number',
    },
    {
      title: 'ProductLimitText',
      name: 'productLimitText',
      description: '',
      type: 'string',
    },
    {
      title: 'FreeShippingThreshold',
      name: 'freeShippingThreshold',
      description: '',
      type: 'number',
    },
    {
      title: 'PromoImageMobile',
      name: 'promoImageMobile',
      description: '',
      type: 'image',
    },
    {
      title: 'PromoImageDesktop',
      name: 'promoImageDesktop',
      description: '',
      type: 'image',
    },
    {
      title: 'AutoDeliveryDiscount',
      name: 'autoDeliveryDiscount',
      description: '',
      type: 'number',
    },
    {
      title: 'AutoDeliveryMessage',
      name: 'autoDeliveryMessage',
      description: '',
      type: 'reference',
      to: [{type: 'autoDeliveryMessage'}],
    },
    {
      title: 'SwitchAutoDeliveryMessage',
      name: 'switchAutoDeliveryMessage',
      ...richBlockType,
    },
    {
      title: 'SellingPlans',
      name: 'sellingPlans',
      description: '',
      type: 'array',
      of: [
        {
          description: '',
          type: 'reference',
          to: [{type: 'sellingPlans'}],
        },
      ],
    },
    {
      title: 'Show_afterpay',
      name: 'show_afterpay',
      description: '',
      type: 'boolean',
    },
    {
      title: 'FreeGiftPromoToggle',
      name: 'freeGiftPromoToggle',
      description: '',
      type: 'boolean',
    },
    {
      title: 'FreeGiftPromoProductExternalID',
      name: 'freeGiftPromoProductExternalID',
      description: '',
      type: 'string',
    },
    {
      title: 'FreeGiftPromoProductPrice',
      name: 'freeGiftPromoProductPrice',
      description: '',
      type: 'string',
    },
    {
      title: 'FreeGiftPromoIsMisteryProductToggle',
      name: 'freeGiftPromoIsMisteryProductToggle',
      description: '',
      type: 'boolean',
    },
    {
      title: 'FreeGiftPromoMysteryImage',
      name: 'freeGiftPromoMysteryImage',
      description: '',
      type: 'image',
    },
    {
      title: 'FreeGiftPromoStartDate',
      name: 'freeGiftPromoStartDate',
      description: '',
      type: 'datetime',
    },
    {
      title: 'FreeGiftPromoStartHour',
      name: 'freeGiftPromoStartHour',
      description: '',
      type: 'number',
    },
    {
      title: 'FreeGiftPromoEndDate',
      name: 'freeGiftPromoEndDate',
      description: '',
      type: 'datetime',
    },
    {
      title: 'FreeGiftPromoEndHour',
      name: 'freeGiftPromoEndHour',
      description: '',
      type: 'number',
    },
    {
      title: 'FreeGiftPromoThreshold',
      name: 'freeGiftPromoThreshold',
      description: '',
      type: 'number',
    },
    {
      title: 'FreeGiftPromoProgressCompleteMessage',
      name: 'freeGiftPromoProgressCompleteMessage',
      description: '',
      type: 'string',
    },
    {
      title: 'FreeGiftPromoCombineAD',
      name: 'freeGiftPromoCombineAD',
      description: '',
      type: 'boolean',
    },
    {
      title: 'EnableCountdownTimerPromo',
      name: 'enableCountdownTimerPromo',
      description: '',
      type: 'boolean',
    },
    {
      title: 'CountdownTimerPromoESTDeadlineDate',
      name: 'countdownTimerPromoESTDeadlineDate',
      description: '',
      type: 'string',
    },
    {
      title: 'CountdownTimerPromoESTDeadlineHour',
      name: 'countdownTimerPromoESTDeadlineHour',
      description: '',
      type: 'string',
    },
    {
      title: 'CountdownTimerPromoCopy',
      name: 'countdownTimerPromoCopy',
      description: '',
      type: 'string',
    },
    {
      title: 'CountdownTimerPromoBannerColor',
      name: 'countdownTimerPromoBannerColor',
      description: '',
      type: 'string',
    },
    {
      title: 'EmptyCartTemporaryWarn',
      name: 'emptyCartTemporaryWarn',
      ...richBlockType,
    },
    {
      title: 'CartTemporaryWarn',
      name: 'cartTemporaryWarn',
      ...richBlockType,
    },
    {
      title: 'ShowTemporaryWarn',
      name: 'showTemporaryWarn',
      description: '',
      type: 'boolean',
    },
  ],
}
