export default {
  name: 'homepageRecommendations',
  description: '',
  type: 'document',
  title: 'HomepageRecommendations',
  fields: [
    {
      title: 'Name',
      name: 'name',
      description: '',
      type: 'string',
    },
    {
      title: 'CollectionOne',
      name: 'collectionOne',
      description: '',
      type: 'reference',
      to: [{type: 'productCollections'}],
    },
    {
      title: 'CollectionOneFontColorHex',
      name: 'collectionOneFontColorHex',
      description: '',
      type: 'string',
    },
    {
      title: 'CollectionOneEmoji',
      name: 'collectionOneEmoji',
      description: '',
      type: 'image',
    },
    {
      title: 'CollectionTwo',
      name: 'collectionTwo',
      description: '',
      type: 'reference',
      to: [{type: 'productCollections'}],
    },
    {
      title: 'CollectionTwoFontColorHex',
      name: 'collectionTwoFontColorHex',
      description: '',
      type: 'string',
    },
    {
      title: 'CollectionTwoEmoji',
      name: 'collectionTwoEmoji',
      description: '',
      type: 'image',
    },
    {
      title: 'CollectionThree',
      name: 'collectionThree',
      description: '',
      type: 'reference',
      to: [{type: 'productCollections'}],
    },
    {
      title: 'CollectionThreeFontColorHex',
      name: 'collectionThreeFontColorHex',
      description: '',
      type: 'string',
    },
    {
      title: 'CollectionThreeEmoji',
      name: 'collectionThreeEmoji',
      description: '',
      type: 'image',
    },
    {
      title: 'CollectionFour',
      name: 'collectionFour',
      description: '',
      type: 'reference',
      to: [{type: 'productCollections'}],
    },
    {
      title: 'CollectionFourFontColorHex',
      name: 'collectionFourFontColorHex',
      description: '',
      type: 'string',
    },
    {
      title: 'CollectionFourEmoji',
      name: 'collectionFourEmoji',
      description: '',
      type: 'image',
    },
  ],
}
