export default {
  name: 'homepageWhyProbiotics',
  description: '',
  type: 'document',
  title: 'HomepageWhyProbiotics',
  fields: [
    {
      title: 'Name',
      name: 'name',
      description: '',
      type: 'string',
    },
    {
      title: 'Header',
      name: 'header',
      description: '',
      type: 'string',
    },
    {
      title: 'SectionCopy',
      name: 'sectionCopy',
      description: '',
      type: 'string',
    },
    {
      title: 'SubheaderOne',
      name: 'subheaderOne',
      description: '',
      type: 'string',
    },
    {
      title: 'SubtextOne',
      name: 'subtextOne',
      description: '',
      type: 'string',
    },
    {
      title: 'SubheaderTwo',
      name: 'subheaderTwo',
      description: '',
      type: 'string',
    },
    {
      title: 'SubtextTwo',
      name: 'subtextTwo',
      description: '',
      type: 'string',
    },
    {
      title: 'SubheaderThree',
      name: 'subheaderThree',
      description: '',
      type: 'string',
    },
    {
      title: 'SubtextThree',
      name: 'subtextThree',
      description: '',
      type: 'string',
    },
    {
      title: 'ButtonText',
      name: 'buttonText',
      description: '',
      type: 'string',
    },
    {
      title: 'ButtonUrl',
      name: 'buttonUrl',
      description: '',
      type: 'string',
    },
    {
      title: 'BigImage',
      name: 'bigImage',
      description: '',
      type: 'image',
    },
    {
      title: 'SmallImage',
      name: 'smallImage',
      description: '',
      type: 'image',
    },
  ],
}
