export default {
  name: 'pressPage',
  description: '',
  type: 'document',
  title: 'PressPage',
  fields: [
    {
      title: 'Name',
      name: 'name',
      description: '',
      type: 'string',
    },
    {
      title: 'TopBanner',
      name: 'topBanner',
      description: '',
      type: 'image',
    },
    {
      title: 'FeaturedBlockOneLogo',
      name: 'featuredBlockOneLogo',
      description: '',
      type: 'image',
    },
    {
      title: 'FeaturedBlockOneText',
      name: 'featuredBlockOneText',
      description: '',
      type: 'string',
    },
    {
      title: 'FeaturedBlockTwoLogo',
      name: 'featuredBlockTwoLogo',
      description: '',
      type: 'image',
    },
    {
      title: 'FeaturedBlockTwoText',
      name: 'featuredBlockTwoText',
      description: '',
      type: 'string',
    },
    {
      title: 'FeaturedBlockThreeLogo',
      name: 'featuredBlockThreeLogo',
      description: '',
      type: 'image',
    },
    {
      title: 'FeaturedBlockThreeText',
      name: 'featuredBlockThreeText',
      description: '',
      type: 'string',
    },
    {
      title: 'FeaturedBlockFourLogo',
      name: 'featuredBlockFourLogo',
      description: '',
      type: 'image',
    },
    {
      title: 'FeaturedBlockFourText',
      name: 'featuredBlockFourText',
      description: '',
      type: 'string',
    },
    {
      title: 'FeaturedBlockFiveLogo',
      name: 'featuredBlockFiveLogo',
      description: '',
      type: 'image',
    },
    {
      title: 'FeaturedBlockFiveText',
      name: 'featuredBlockFiveText',
      description: '',
      type: 'string',
    },
    {
      title: 'FeaturedBlockSixLogo',
      name: 'featuredBlockSixLogo',
      description: '',
      type: 'image',
    },
    {
      title: 'FeaturedBlockSixText',
      name: 'featuredBlockSixText',
      description: '',
      type: 'string',
    },
    {
      title: 'ArticleOneImage',
      name: 'articleOneImage',
      description: '',
      type: 'image',
    },
    {
      title: 'ArticleOneLogo',
      name: 'articleOneLogo',
      description: '',
      type: 'image',
    },
    {
      title: 'ArticleOnePreviewText',
      name: 'articleOnePreviewText',
      description: '',
      type: 'string',
    },
    {
      title: 'ArticleOneLink',
      name: 'articleOneLink',
      description: '',
      type: 'string',
    },
    {
      title: 'ArticleTwoImage',
      name: 'articleTwoImage',
      description: '',
      type: 'image',
    },
    {
      title: 'ArticleTwoLogo',
      name: 'articleTwoLogo',
      description: '',
      type: 'image',
    },
    {
      title: 'ArticleTwoPreviewText',
      name: 'articleTwoPreviewText',
      description: '',
      type: 'string',
    },
    {
      title: 'ArticleTwoLink',
      name: 'articleTwoLink',
      description: '',
      type: 'string',
    },
    {
      title: 'ArticleThreeImage',
      name: 'articleThreeImage',
      description: '',
      type: 'image',
    },
    {
      title: 'ArticleThreeLogo',
      name: 'articleThreeLogo',
      description: '',
      type: 'image',
    },
    {
      title: 'ArticleThreePreviewText',
      name: 'articleThreePreviewText',
      description: '',
      type: 'string',
    },
    {
      title: 'ArticleThreeLink',
      name: 'articleThreeLink',
      description: '',
      type: 'string',
    },
    {
      title: 'ArticleFourImage',
      name: 'articleFourImage',
      description: '',
      type: 'image',
    },
    {
      title: 'ArticleFourLogo',
      name: 'articleFourLogo',
      description: '',
      type: 'image',
    },
    {
      title: 'ArticleFourPreviewText',
      name: 'articleFourPreviewText',
      description: '',
      type: 'string',
    },
    {
      title: 'ArticleFourLink',
      name: 'articleFourLink',
      description: '',
      type: 'string',
    },
    {
      title: 'ArticleFiveImage',
      name: 'articleFiveImage',
      description: '',
      type: 'image',
    },
    {
      title: 'ArticleFiveLogo',
      name: 'articleFiveLogo',
      description: '',
      type: 'image',
    },
    {
      title: 'ArticleFivePreviewText',
      name: 'articleFivePreviewText',
      description: '',
      type: 'string',
    },
    {
      title: 'ArticleFiveLink',
      name: 'articleFiveLink',
      description: '',
      type: 'string',
    },
    {
      title: 'ArticleSixImage',
      name: 'articleSixImage',
      description: '',
      type: 'image',
    },
    {
      title: 'ArticleSixLogo',
      name: 'articleSixLogo',
      description: '',
      type: 'image',
    },
    {
      title: 'ArticleSixPreviewText',
      name: 'articleSixPreviewText',
      description: '',
      type: 'string',
    },
    {
      title: 'ArticleSixLink',
      name: 'articleSixLink',
      description: '',
      type: 'string',
    },
    {
      title: 'ProductRecommendationHeader',
      name: 'productRecommendationHeader',
      description: '',
      type: 'string',
    },
    {
      title: 'ProductRecommendationSubHeader',
      name: 'productRecommendationSubHeader',
      description: '',
      type: 'string',
    },
    {
      title: 'ProductRecommendations',
      name: 'productRecommendations',
      description: '',
      type: 'reference',
      to: [{type: 'productCollections'}],
    },
    {
      title: 'SeoTitle',
      name: 'seoTitle',
      description: '',
      type: 'string',
    },
    {
      title: 'SeoDescription',
      name: 'seoDescription',
      description: '',
      type: 'string',
    },
    {
      title: 'SeoUrl',
      name: 'seoUrl',
      description: '',
      type: 'string',
    },
  ],
}
