export default {
  name: 'tulaScholarshipPage',
  description: '',
  type: 'document',
  title: 'TulaScholarshipPage',
  fields: [
    {
      title: 'Name',
      name: 'name',
      description: '',
      type: 'string',
    },
    {
      title: 'content',
      name: 'Content',
      description: '',
      type: 'array',
      of: [{type: 'block'}],
    },
    {
      title: 'contentTwo',
      name: 'ContentTwo',
      description: '',
      type: 'array',
      of: [{type: 'block'}],
    },
    {
      title: 'contentThree',
      name: 'ContentThree',
      description: '',
      type: 'array',
      of: [{type: 'block'}],
    },
    {
      title: 'contentFour',
      name: 'ContentFour',
      description: '',
      type: 'array',
      of: [{type: 'block'}],
    },
    {
      title: 'contentFive',
      name: 'ContentFive',
      description: '',
      type: 'array',
      of: [{type: 'block'}],
    },
    {
      title: 'contentSix',
      name: 'ContentSix',
      description: '',
      type: 'array',
      of: [{type: 'block'}],
    },
    {
      title: 'contentSeven',
      name: 'ContentSeven',
      description: '',
      type: 'array',
      of: [{type: 'block'}],
    },
    {
      title: 'contentEight',
      name: 'ContentEight',
      description: '',
      type: 'array',
      of: [{type: 'block'}],
    },
    {
      title: 'contentNine',
      name: 'ContentNine',
      description: '',
      type: 'array',
      of: [{type: 'block'}],
    },
    {
      title: 'contentTen',
      name: 'ContentTen',
      description: '',
      type: 'array',
      of: [{type: 'block'}],
    },
    {
      title: 'contentEleven',
      name: 'ContentEleven',
      description: '',
      type: 'array',
      of: [{type: 'block'}],
    },
  ],
}
