# Don't change the line below!
#! oxygen_storefront_id: 1000016926

name: Storefront 1000016926
on:
  pull_request:
    branches:
      - uk-main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo yo