# Don't change the line below!
#! oxygen_storefront_id: 1000005119

name: Storefront 1000005119
on:
  push:
    branches:
      - staging

permissions:
  contents: read
  deployments: write

jobs:
  deploy-hydrogen:
    name: Deploy to Oxygen Staging
    timeout-minutes: 30
    if: ${{ contains(github.event.head_commit.message, 'Merge pull request') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          check-latest: true

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Publish to Oxygen Staging
        id: deploy
        uses: shopify/oxygenctl-action@v4
        with:
          oxygen_worker_dir: "./apps/hydroxy/dist/worker"
          oxygen_client_dir: "./apps/hydroxy/dist/client"
          oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_1000005119 }}
          build_command: "HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL npm run build:hydroxy"
  
  deploy-sanity:
      name: Deploy Sanity Staging
      runs-on: ubuntu-latest
      env: 
        SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }} 

      if: ${{ contains(github.event.head_commit.message, 'Merge pull request') }}

      steps:
          - uses: actions/checkout@v3

          - name: Setup node.js
            uses: actions/setup-node@v3
            with:
              node-version: '20'
              check-latest: true

          - name: Install dependencies
            run: |
                npm ci

          - name: Deploy Sanity Studio
            run: |
                npm run deploy:sanity-studio

          - name: Deploy Sanity Staging GraphQL API
            run: |
                npm run deploy:sanity-api staging